# Delete these routes and define your own shop routes here

acme_sylius_example_admin:
    resource: "@AcmeSyliusExamplePlugin/config/routes/admin.yaml"

acme_sylius_example_shop:
    resource: "@AcmeSyliusExamplePlugin/config/routes/shop.yaml"
